site_name: Duon Wire
copyright: © 2023-2024 ebene fünf GmbH
nav:
  - Documentation:
    - 'Introduction': index.md
    - 'The Creator': creator.md
    - resolvers.md
    - 'PSR-11 Containers': container.md
    - call-attribute.md
    - inject-attribute.md
  - Resources:
    - changelog.md
    - license.md
theme:
  name: duon
repo_url: https://github.com/duon/wire
extra:
  project: Wire
plugins:
  - search
  - macros:
      module_name: docs/main
markdown_extensions:
  - admonition
  - pymdownx.snippets:
      base_path: [".", "docs/code"]